version: "3.8"

services:
  keycloak:
    build: ./keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: keycloak
      KC_BOOTSTRAP_ADMIN_PASSWORD: keycloak
    ports:
      - 8080:8080
  kong:
    image: kong:latest
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
    volumes:
      - ./kong.yml:/etc/kong/kong.yml
    depends_on:
      - profile
      - citation
      - images
      - swagger

  profile:
    build: ./profiles-api
    ports:
      - 9080:8080
    environment:
      spring_profiles_active: security,docker
    depends_on:
      - mongo

  citation:
    build: ./citations-api
    ports:
      - 9081:8080
    environment:
      spring_profiles_active: security,docker
    depends_on:
      - mongo

  images:
    build: ./images-api
    ports:
      - 9082:8080
    environment:
      spring_profiles_active: security,docker

  swagger:
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON: /doc/citations.yaml
      DEEP_LINKING: "true"
      OAUTH2_REDIRECT_URL: http://localhost:8888/oauth2-redirect.html
      OAUTH_CLIENT_ID: swagger
      OAUTH_USE_PKCE: "true"
      OAUTH_REALM: tindeer
      OAUTH_APP_NAME: swagger
      PROXY_URL: http://localhost:8000

    ports:
      - 8888:8080
    volumes:
      - ./swagger:/doc

  mongo:
    image: mongo
    ports:
      - "27017:27017"