openapi: 3.0.0
info:
  title: One Citations API
  description: Notre super API pour notre application de gestions des citations
  version: 1.0.0
servers:
  - url: http://localhost:9080/api/v1
    description: Environnement de test Docker
  - url: http://localhost:9090/api/v1
    description: Environnement de test local
components:
  securitySchemes:
    oAuthSample:    # <---- arbitrary name
      type: oauth2
      description: This API uses OAuth 2 with the implicit grant flow. [More info](https://api.example.com/docs/auth)
      flows:
        authorizationCode:   # <---- OAuth flow(authorizationCode, implicit, password or clientCredentials)
          authorizationUrl: http://keycloak:8080/realms/one-citations/protocol/openid-connect/auth
          tokenUrl: http://keycloak:8080/realms/one-citations/protocol/openid-connect/token
          scopes:
            profile: access profile
            email: access email
  schemas:
    ProfileDto:
      type: object
      properties:
        id:
          type: string
          description: Identifiant unique du profil
        userId:
          type: string
          description: Identifiant unique de l'utilisateur
        mail:
          type: string
          format: email
          description: Adresse e-mail de l'utilisateur
        age:
          type: integer
          minimum: 13
          description: Âge de l'utilisateur (minimum 13 ans)
        firstName:
          type: string
          description: Prénom de l'utilisateur
        lastName:
          type: string
          description: Nom de famille de l'utilisateur
      required:
        - userId
        - mail
    PageDto:
      type: object
      properties:
        pageSize:
          type: integer
          description: Nombre d'éléments par page
        totalElements:
          type: integer
          description: Nombre total d'éléments
        next:
          type: string
          format: uri
          description: URI pour la page suivante
        first:
          type: string
          format: uri
          description: URI pour la première page
        last:
          type: string
          format: uri
          description: URI pour la dernière page
        data:
          type: array
          description: Données de la page
          items:
            $ref: '#/components/schemas/ProfileDto'
    CitationDto:
      type: object
      properties:
        id:
          type: string
          description: Identifiant unique de la citation
        text:
          type: string
          description: Le texte de la citation
        authorId:
          type: string
          description: Identifiant de l'auteur
        validatorId:
          type: string
          description: Identifiant du validateur
        submissionDate:
          type: string
          format: date-time
          description: La date et l'heure de soumission
        modificationDate:
          type: string
          format: date-time
          description: La date et l'heure de la dernière modification
        validated:
          type: boolean
          description: Statut de validation de la citation

security:
  - oAuthSample:
      - profile
      - email
paths:
  /profiles/current:
    get:
      summary: Retourne le profil courant de l'utilisateur
      responses:
        '200':
          description: Profil de l'utilisateur courant
          content:
            application/json:
              schema:
                type: object
                properties:
                  principal:
                    type: object

  /profiles/{id}:
    get:
      summary: Récupère un profil par son ID
      parameters:
        - name: id
          in: path
          required: true
          description: Identifiant du profil
          schema:
            type: string
      responses:
        '200':
          description: Profil récupéré avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfileDto'
    put:
      summary: Met à jour un profil existant
      parameters:
        - name: id
          in: path
          required: true
          description: Identifiant du profil
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProfileDto'
      responses:
        '200':
          description: Profil mis à jour avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfileDto'

  /profiles:
    post:
      summary: Crée un nouveau profil
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProfileDto'
      responses:
        '201':
          description: Profil créé avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfileDto'

  /profiles/search:
    get:
      summary: Recherche des profils par query (RSQL)
      parameters:
        - name: query
          in: query
          required: false
          description: Requête de recherche RSQL
          schema:
            type: string
        - name: page
          in: query
          required: false
          description: Numéro de la page
          schema:
            type: integer
        - name: size
          in: query
          required: false
          description: Taille de la page
          schema:
            type: integer
      responses:
        '200':
          description: Résultats de la recherche
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageDto'

  /profiles/search/mail:
    get:
      summary: Recherche des profils par adresse e-mail
      parameters:
        - name: mail
          in: query
          required: true
          description: Adresse e-mail à rechercher
          schema:
            type: string
        - name: page
          in: query
          required: false
          description: Numéro de la page
          schema:
            type: integer
        - name: size
          in: query
          required: false
          description: Taille de la page
          schema:
            type: integer
      responses:
        '200':
          description: Résultats de la recherche par e-mail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageDto'
  /citations/random:
    get:
      summary: Retourne une citation validée aléatoire
      responses:
        '200':
          description: Citation aléatoire
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CitationDto'

  /citations:
    post:
      summary: Soumettre une nouvelle citation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CitationDto'
      responses:
        '201':
          description: Citation soumise avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CitationDto'

  /citations/unvalidated:
    get:
      summary: Récupère toutes les citations non validées
      security:
        - oAuthSample: [ profile ]
      responses:
        '200':
          description: Liste des citations non validées
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CitationDto'

  /citations/{id}/validate:
    put:
      summary: Valider une citation
      parameters:
        - name: id
          in: path
          required: true
          description: Identifiant de la citation à valider
          schema:
            type: string
      security:
        - oAuthSample: [ profile ]
      responses:
        '200':
          description: Citation validée avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CitationDto'